# Connects to GPU 0 and listens on port 11500
services:
  ollama-gpu-0:
    image: ollama/ollama:rocm
    container_name: ollama-gpu-0
    runtime: amd
    environment:
      - OLLAMA_HOST=0.0.0.0:11500
      # Using the correct environment variable for device visibility
      - ROCR_VISIBLE_DEVICES="0"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    volumes:
      # Use your host's model cache
      - /usr/share/ollama/.ollama:/root/.ollama
    network_mode: host
    restart: unless-stopped
